site_name: My Docs
#site_url: https://ahmadal-quraan.github.io/Inception/
theme: 
  name: material
plugins:
  - search
  - callouts

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
