site_name: Inception
docs_dir: docs/
theme:
  name: material
  logo: pic/logo.png
  favicon: pic/logo.png
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - obsidian-bridge:
      obsidian_callouts: true
extra:
  obsidian_attachments_dir: docs/pic/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
